version: 1.6.{build}
init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
branches:
  only:
    - master
    - /new.*/
before_build:
  - cmd: nuget restore BikeTracker.sln
  - cmd: npm --version
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\BikeTracker && npm install && cd %APPVEYOR_BUILD_FOLDER%
build:
  project: BikeTracker.sln
  verbosity: minimal
skip_tags: true
before_test:
  - cmd: mkdir %APPVEYOR_BUILD_FOLDER%\reports\coverage\history
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && nuget install OpenCover -ExcludeVersion -OutputDirectory tools
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && nuget install xunit.runner.console -ExcludeVersion -OutputDirectory tools
test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && set APPVEYOR_API_URL= && tools\OpenCover\tools\OpenCover.Console.exe -target:"tools\xunit.runner.console\tools\xunit.console.x86.exe" -targetargs:"BikeTracker.XTests\bin\Debug\BikeTracker.XTests.dll -noShadow -xml test-results.xml" -register:user -output:"reports\coverage\coverage.xml" -skipautoprops -filter:"+[BikeTracker*]* -[BikeTracker*]BikeTracker.Migrations* -[BikeTracker.XTests*]*"  -excludebyattribute:*.ExcludeFromCodeCoverage* -mergebyhash -returntargetcode -coverbytest:*.XTest.dll
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\BikeTracker && node_modules\.bin\karma.cmd start --single-run && cd %APPVEYOR_BUILD_FOLDER%
after_test:
  - ps: .\upload-results.ps1
  - cmd: tools\coveralls.io\tools\coveralls.net.exe --autodetect reports\coverage\coverage.xml reports\karma-results\xml\cobertura-coverage.xml
environment:
  COVERALLS_REPO_TOKEN:
    secure: Vw+qs3QR9AkkoHIIZUqHX2oaD2a6wmb+fhCByIEKmFuQBabbl7H8bra+jkdoa/Tr
  Production_Build_Path:
    secure: YWpSkUKKRmU10IaqzStD0v9ioYz9eQ4QZeDNme54/h3iaCjGcXlmIgmgk8oGGfP7kKgdUJIhEiJ6AtoTqSggQ5JHM0yIcCCCSxi+Qt2VZ1byohifJCuR2lpXwYnN7nxfW3fp0ptrZEzi754kyKFaVU9NQk4Fohc6u2U+U+VM67g=]
  nodejs_version: "6"
deploy:
- provider: GitHub
  on:
    branch: master
  auth_token:
    secure: jB6EhCv7m6D+5LBhRTBrlFlXK3tk8Tk5PLbWJVniY22kMaMIFBQT7DoO43axvFfm
  draft: false
  prerelease: false
after_deploy:
- ps: .\deploy.ps1
